package sharedClasses.transferObject;

public enum EventType
{
  LOGIN_RESULT,
  LOGIN_REQUEST,
  REGISTER_RESULT,
  REGISTER_REQUEST,
  USERSLIST_RESULT,
  USERSLIST_REQUEST,
  DUEL_REQUEST,
  DUEL_RESULT,
  OPEN_GAME_VIEW_REQUEST,
  OPEN_GAME_VIEW_RESULT,
  SHUFFED_DECK_RESULT,
  SHUFFED_DECK_REQUEST,
  GET_FIRST_TURN_REQUEST,
  GET_FIRST_TURN_RESULT,
  SET_OPENED_CARD_TWO_ARG,
  KEEP_OPEN;
}
